### ISSUE TITLE
ModuleNotFoundError: No module named 'Transformer'

### ISSUE THREAD

**Issue by Valentin-Bio** [fannyhb/fargene#12]
Hello I made  amanually installation of fargene by cloning the repository on my server . also I  checked if the dependencies were installed
I created a new conda environment and installed python 2.7

under that environment I installed EMBOSS , spades, hmmer orffinder trim-galore and seqtk.

When I run `fargene -h` I got the following error message "ModuleNotFoundError: No module named 'Transformer'"

This is the full error message:

**Traceback (most recent call last):
  File "/datos/vberrios/miniconda3/envs/biopython/bin/fargene", line 33, in <module>
    sys.exit(load_entry_point('fargene==0.1', 'console_scripts', 'fargene')())
  File "/datos/vberrios/miniconda3/envs/biopython/bin/fargene", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/datos/vberrios/miniconda3/envs/biopython/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/datos/vberrios/miniconda3/envs/biopython/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/datos/vberrios/miniconda3/envs/biopython/lib/python3.9/site-packages/fargene-0.1-py3.9.egg/fargene_analysis/fargene_analysis.py", line 12, in <module>
    from Transformer import Transformer
ModuleNotFoundError: No module named 'Transformer'
(fargene_2try) [vberrios@dylan vberrios]$ conda activate fargene
(fargene) [vberrios@dylan vberrios]$ fargene
Traceback (most recent call last):
  File "/datos/vberrios/miniconda3/envs/biopython/bin/fargene", line 33, in <module>
    sys.exit(load_entry_point('fargene==0.1', 'console_scripts', 'fargene')())
  File "/datos/vberrios/miniconda3/envs/biopython/bin/fargene", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/datos/vberrios/miniconda3/envs/biopython/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/datos/vberrios/miniconda3/envs/biopython/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/datos/vberrios/miniconda3/envs/biopython/lib/python3.9/site-packages/fargene-0.1-py3.9.egg/fargene_analysis/fargene_analysis.py", line 12, in <module>
    from Transformer import Transformer
ModuleNotFoundError: No module named 'Transformer'**

**Comment by Valentin-Bio** [comment]
Solved by installing it using conda recipe

`conda install -c conda-forge -c bioconda fargene`
