### ISSUE TITLE
Model creation

### ISSUE THREAD

**Issue by IfkaK** [fannyhb/fargene#6]
Hi, 
I have some troubles when creating my own models. Please, do you have any idea how to fix it, where to add a closing quotation...? 
Fargene installed via conda. Analyzing metagenomic data is fine, everything is working properly.  
Thanks and have a nice day.

fargene_model_creation --reference-sequences /home/kotaskova/data/model/input/kasugamycin_70.fasta --negative-sequences /home/kotaskova/data/model/input/kasuga_neg_70.fasta --modelname kasuga

Estimating sensitivity for full length genes...
Traceback (most recent call last):
  File "/home/kotaskova/.conda/envs/ifkafargene/bin/fargene_model_creation", line 11, in <module>
    load_entry_point('fargene==0.1', 'console_scripts', 'fargene_model_creation')()
  File "/home/kotaskova/.conda/envs/ifkafargene/lib/python2.7/site-packages/fargene_model_creation/create_and_optimize_model.py", line 82, in main
    estimate_sensitivity(options.reference_sequences,est_obj,options)
  File "/home/kotaskova/.conda/envs/ifkafargene/lib/python2.7/site-packages/fargene_model_creation/estimate_sensitivity.py", line 34, in estimate_sensitivity
    create_model(modelfile, alignfile, hmmfile)
  File "/home/kotaskova/.conda/envs/ifkafargene/lib/python2.7/site-packages/fargene_model_creation/estimate_sensitivity.py", line 128, in create_model
    commands = shlex.split(call_list)
  File "/home/kotaskova/.conda/envs/ifkafargene/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/home/kotaskova/.conda/envs/ifkafargene/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/home/kotaskova/.conda/envs/ifkafargene/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/home/kotaskova/.conda/envs/ifkafargene/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation

**Comment by fannyhb** [comment]
Hi,

I think the issue might be that the headers in your reference file contain quotation marks.  What happens is that fARGene creates separate files of each sequence in your reference fasta file and it uses the header for each sequence to create the filename. I will fix this bug so that it can handle quotation marks and other unusual characters in the headers, but in the meantime I suggest that you just replace these in your headers with an underscore or similar.
Hope this helps.

Fanny

**Comment by IfkaK** [comment]
Hi Fanny, 
thanks a lot for advice, I have replaced quotation marks in few fasta headers (and all other special characters such as full stops), and everything is fine now.  
Thank you very much and have a nice day.
