### ISSUE TITLE
fargene run error: no module named "Transformers"

### ISSUE THREAD

**Issue by EmilyB17** [fannyhb/fargene#7]
Hello,
I am trying to install and run fargene via instructions on the `README.md`. Here is the error I get:

[epb5360@aci-lgn-008 amrfargene]$ fargene
Traceback (most recent call last):
  File "/storage/home/epb5360/.local/bin/fargene", line 11, in <module>
    load_entry_point('fargene==0.1', 'console_scripts', 'fargene')()
  File "/opt/aci/sw/python/3.6.3_anaconda-5.0.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/aci/sw/python/3.6.3_anaconda-5.0.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/opt/aci/sw/python/3.6.3_anaconda-5.0.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/opt/aci/sw/python/3.6.3_anaconda-5.0.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/storage/home/epb5360/.local/lib/python3.6/site-packages/fargene-0.1-py3.6.egg/fargene_analysis/fargene_analysis.py", line 12, in <module>
    from Transformer import Transformer
**ModuleNotFoundError: No module named 'Transformer'**

**Comment by fannyhb** [comment]
Dear Emily,

it seems like you are installing fARGene using python version 3.6, however, fARGene is developed to be used with python version 2.x.
To solve this issue, try installing fARGene in an environment that has python v 2.x (such as another conda environment with python 2.x).

Best Regards
Fanny

**Comment by GomathiNayagam** [comment]
Hi Fanny,
I created a python 2.7 environment in conda, but while installing numpy seems to require python 3.7. Could you help me?
